# Application
spring.application.name=Pek Security
application.version=0.0.1-SNAPSHOT

# Logger
logging.level.root=info
logging.level.com.peknight.security=debug
logging.file=security/log/security

# Console Output Color
spring.output.ansi.enabled=always

# Datasource
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/security?characterEncoding=utf-8&useSSL=true
spring.datasource.username=test
spring.datasource.password=e=$_SKMWhtsq3ccI